### ISSUE TITLE
Vertragsbeginn wird falsch angezeigt/gespeichert

### ISSUE THREAD

**Issue by To0m** [rookian1337/contract-reminder#2]
<img width="729" alt="bildschirmfoto 2015-09-22 um 17 45 16" src="https://cloud.githubusercontent.com/assets/4105789/10023311/bef3154e-6151-11e5-974a-691d1f71847f.png">

Vertragsbeginn wird falsch angezeigt/gespeichert, "Kündigung möglich zum" wird aber korrekt berechnet.

**Comment by rookian1337** [comment]
Das Datum wurde fälschlicherweise als 0000-00-00 gespeichert.

Wurde in 87e7a78eab1fc999bbfe90083f8e339e71f6b205 gefixed.
